title: Inglo Games
description: Homepage
author: Inglo Games
logo: /static/img/bulb.png
github: https://github.com/Inglo-Games
about: Indie Game Studio

baseurl: ""
url: ""

allowsearch: false

disqus_shortname: IngloGames
google_analytics: UA-148359985-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
